name: Secrets Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.SUPERSECRET  }}
      super_secret2: ${{ secrets.SUPERSECRET  }}
    steps:
      - name: Run Commands with a Secret
        if: ${{ env.super_secret != '' }}
        run: echo 'TEM INFORMAÇÂO'
      - if: ${{ env.super_secret == '' }}
        run: echo 'NÃO TEM INFORMAÇÃO'
