name: Secrets Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands with a Secret
        env:
          super_secret: ${{ secrets.APITOKEN }}
        if: ${{ env.super_secret != '' }}
        run: echo 'TEM INFORMAÇÂO'
      - if: ${{ env.super_secret == '' }}
        run: echo 'NÃO TEM INFORMAÇÃO'
