name: Environment Variables Workflow

on: [push]

env:
  WORKFLOW_VARIABLE: WORKFLOW

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: JOB
    steps:
      - name: Run Commands with various variables
        if: ${{ env.WORKFLOW_VARIABLE == 'WORKFLOW' }} # Example using context env
        env:
          STEP_VARIABLE: STEP
          super_secret: ${{ secrets.GITHUB_TOKEN }}
          super_tokenapi: ${{ secrets.Aprendendo.APITOKEN }}
          super_SUPERSECRET: ${{ secrets.SUPERSECRET }}
        run: |
          echo "Hello World"
          echo "This is the $WORKFLOW_VARIABLE environment variable"
          echo "This is the $JOB_VARIABLE environment variable"
          echo "This is the $STEP_VARIABLE environment variable"
          echo "This is the $super_secret environment variable"
          echo "This is the $super_tokenapi environment variable"
          echo "This is the $super_SUPERSECRET environment variable"
