name: Complete workflow

on: ["push"]

env:
  APITOKEN: ${{secrets.SECRETTESTE}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run all tests
        run: yarn test:unit

      # - shell: bash
      # if: github.ref == 'ref/heads/main'
      # name: Cria um SSH de ket deploy
      # env:
      #   SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      # run: ./scripts/deplay.sh
