name: Secrets Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{ secrets.SUPERSECRET  }}
      teste: tes1
    steps:
      - name: Run Commands with a Secret
        if: ${{ env.super_secret != '' }}
        run: echo 'TEM INFORMAÇÂO env.teste'
      - if: ${{ env.super_secret == '' }}
        run: echo 'NÃO TEM INFORMAÇÃO env.teste'
